### ISSUE TITLE
about the pretrained ConvNeXt model

### ISSUE THREAD

**Issue by wyf0414** [WayneMao/PillarNeSt#1]
Hi, thanks for open sourcing this brilliant work!

I read your paper in detail. You use ConvNeXt as the pretrained model of PointPillars. This is very pioneering.

I want to know:
Does the pretrained model has the same architecture as your lidar backbone?
Does the pretrained model also has large kernal (like 7*7 in the paper) ?

If possible, can you provide the way to download your pretrained model?

**Comment by WayneMao** [comment]
I'm so sorry for the late response. Recently, I've been busy with my doctoral thesis. 

Sure, the pretrained weights include a convolution with a 7x7 kernel.
If you need the weights immediately, the ConvNeXt weights I used are from mmcls==0.22.1.

https://github.com/open-mmlab/mmpretrain/tree/v0.22.1

**Comment by WayneMao** [comment]
More specifically, the image weights are pretrained on ImageNet-1k.
https://github.com/open-mmlab/mmpretrain/tree/master/configs/convnext

**Comment by wyf0414** [comment]
Thanks very much!
