### ISSUE TITLE
the code for ConvNeXt_PC module 

### ISSUE THREAD

**Issue by hanmuchunhua** [WayneMao/PillarNeSt#3]
Hello, thanks for your great work! I wonder if i could get your implenmention for ConvNeXt_PC since it seems like modified from ConvNeXt.

**Comment by WayneMao** [comment]
Hi, please refer to recent updates:
https://github.com/WayneMao/PillarNeSt/blob/main/projects/mmdet3d_plugin/models/backbones/convnext_pc.py
If you have an emergency, you can send an email to maowx2017@fuji.waseda.jp

**Comment by hanmuchunhua** [comment]
Thank you for your generosity! I couldn't wait to try your updates today, finding that the centerpoint_bbox_coder in 'CenterPlusHead' is different from the 'CenterHead', while the latter missing the 'iou_scores' params. I record to the paper
trying to complete based on 'CenterPointBBoxCoder', but the mAP is not ideal. Here is my implementation
## add iou_scores in `CenterPointBBoxCoder
## first change
iou_scores = self._transpose_and_gather_feat(iou_scores, inds)
iou_scores = iou_scores.view(batch, self.max_num)

## second change
iou_scores = iou_scores[i, cmask]
      predictions_dict = {
          'bboxes': boxes3d,
          'scores': scores,
          'labels': labels,
          'iou_scores':iou_scores }
     predictions_dicts.append(predictions_dict)

I wonder if you please see whether it is what u mean and I could get your own implementation! Thank you so much!

**Comment by WayneMao** [comment]
I'm sorry, but I'm not quite sure I understand your point. For the calculation of the IoU score, please refer to: 
https://github.com/WayneMao/PillarNeSt/blob/main/projects/mmdet3d_plugin/models/dense_heads/centerpoint_plus_head.py#L102
https://github.com/WayneMao/PillarNeSt/blob/main/projects/mmdet3d_plugin/models/dense_heads/centerpoint_plus_head.py#L166
Please refer to section III.A of the paper for specific modifications to the Strong Baseline. In fact, the gain in the IoU score is not significant; it requires the use of the Pillar encoder, IoU score, and training strategy together.

**Comment by hanmuchunhua** [comment]
Hello, I'am appreciated for your reply ! Here to bother you again! I had trained the model without Iou Score using the original CenterPoint head and the ConvNeXt_PC module and Height Pillar Encoder module, but the mAP is still not ideal. I wonder if I
could get more training strategies to reproduce. 

In addition, I mean during inference, when i use the CenterPlusHead,            
 [temp = self.bbox_coder.decode(](https://github.com/WayneMao/PillarNeSt/blob/7dd8108cd25e0af16535899289c72571010a5475/projects/mmdet3d_plugin/models/dense_heads/centerpoint_plus_head.py#L269) 
this line report an error that key params` iou_scores=batch_iou` is not needed, so i wonder if you define a new boxcoder so i could get your modified version of  'CenterPointBBoxCoder'

Thank you so much !

**Comment by WayneMao** [comment]
Great question. I previously overlooked that I indeed redefined a CenterPointBBoxCoder.
Now, I have uploaded the new CenterPointBBoxCoder.
https://github.com/WayneMao/PillarNeSt/blob/main/projects/mmdet3d_plugin/core/bbox/coder/centerpoint_bbox_coders.py
