### ISSUE TITLE
Don't have SEPFNLayer, SEPFNLayerV2

### ISSUE THREAD

**Issue by wuhaozhong-01** [WayneMao/PillarNeSt#4]
I tried to use your code in mmdection3d, but I found that SEPFNLayer, SEPFNLayerV2 used in pillar_encoder.py does not provide it.

**Comment by WayneMao** [comment]
Hi, please refer to recent updates:
https://github.com/WayneMao/PillarNeSt/blob/main/projects/mmdet3d_plugin/models/voxel_encoders/utils.py

If you have an emergency, you can send an email to maowx2017@fuji.waseda.jp

**Comment by wuhaozhong-01** [comment]
Thank you for your response and for making the code open-source.
