### ISSUE TITLE
Questions Regarding Channel Changes in Backbone and PointPillarScatter Dimensions

### ISSUE THREAD

**Issue by GTing31** [WayneMao/PillarNeSt#5]
Hello,

First of all, thank you for your excellent project—it's both impressive and incredibly useful. Your work has been a great inspiration to me.

I have some questions regarding the channel configurations in the backbone:

In both Table 1 and the code, the channels for **ConvNeXt_PC_base** are defined as **[64, 192, 384, 384, 384]**, with the neck being 384 channels. However, in Figure 2 of your architecture diagram, the inputs are shown as **c, [2c, 2c, 4c, 4c, 4c]**. In the final neck, stages 3, 4, and 5 are adjusted to **(c, h/4, w/4)** before concatenation, resulting in a neck output of 3c (which would be 64 * 3). This has left me a bit confused about which configuration is correct. Could you please clarify if there's a discrepancy between the diagram and the implementation, or if I might have misunderstood something?

Additionally, I noticed that in PointPillarScatter, the size is set to (720, 720) instead of the original grid size. Could you explain the reason for this choice? What advantages does setting it to (720, 720) provide?

Thank you very much for your time and assistance

Best regards

**Comment by WayneMao** [comment]
Regarding the first question, please refer to the code and Table Ⅱ, they are the final version and correct.

In fact, there is no original grid size. Grid map depend on grid size, the grid size can reference table Ⅲ. Many papers use a grid size of 0.15. Smaller grid sizes lead to finer results, 0.075 is too small and causes too much computational cost.
